### ISSUE TITLE
Can't initialize Single AWS CF Template - npm error

### ISSUE THREAD

**Issue by ghost** [aws-solutions/liveness-detection-framework#15]
**Describe the bug**
Can't initialize Single AWS CF Template - npm error

**To Reproduce**
- Execute ./build-s3-dist.sh $DIST_OUTPUT_BUCKET liveness-detection-framework v1.0.0 --no-suffix

**Expected behavior**
CloudFormation template should be up and running along with the S3 bucket.

**Please complete the following information about the solution:**
- Python 3.11.1
- Node v18.13.0
- Npm 8.19.3

At the start, I couldn't build wheels for numpy, with error message: ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

This was fixed by changing the numpy version in the source/backend/requirements.txt file from 1.22.0 to 1.24.1

But now, we recieve another error at the "chalice package --merge-template resources.yaml $template_tmp_dir" stage of the build-s3-dist.sh script:

Could not install dependencies:
numpy==1.24.1
wrapt==1.14.1
You will have to build these yourself and vendor them in
the chalice vendor folder.

Your deployment will continue but may not work correctly
if missing dependencies are not present. For more information:
http://aws.github.io/chalice/topics/packaging.html

npm ERR! code EUSAGE
npm ERR! 
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
npm ERR! [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pektezola/.npm/_logs/2023-01-23T13_24_42_753Z-debug-0.log

Full log:
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.19.3
2 info using node@v18.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/pektezola/Commencis/Code/liveness-detection-framework/source/client/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/Users/pektezola/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm ci
23 verbose argv "ci"
24 timing npm:load:setTitle Completed in 5ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/Users/pektezola/.npm/_logs
28 verbose logfile /Users/pektezola/.npm/_logs/2023-01-23T13_24_42_753Z-debug-0.log
29 timing npm:load:logFile Completed in 2ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 17ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile start cleaning logs, removing 7 files
35 verbose loadVirtual Error: loadVirtual requires existing shrinkwrap file
35 verbose loadVirtual     at Arborist.loadVirtual (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:63:18)
35 verbose loadVirtual     at async CI.exec (/usr/local/lib/node_modules/npm/lib/commands/ci.js:37:5)
35 verbose loadVirtual     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
36 timing command:ci Completed in 3ms
37 verbose stack Error: 
37 verbose stack The `npm ci` command can only install with an existing package-lock.json or
37 verbose stack npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
37 verbose stack later to generate a package-lock.json file, then try again.
37 verbose stack
37 verbose stack Clean install a project
37 verbose stack
37 verbose stack Usage:
37 verbose stack npm ci
37 verbose stack
37 verbose stack Options:
37 verbose stack [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
37 verbose stack [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
37 verbose stack [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
37 verbose stack [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
37 verbose stack [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
37 verbose stack [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
37 verbose stack [-ws|--workspaces] [--include-workspace-root] [--install-links]
37 verbose stack
37 verbose stack aliases: clean-install, ic, install-clean, isntall-clean
37 verbose stack
37 verbose stack Run "npm help ci" for more info
37 verbose stack     at CI.usageError (/usr/local/lib/node_modules/npm/lib/base-command.js:88:26)
37 verbose stack     at /usr/local/lib/node_modules/npm/lib/commands/ci.js:43:18
37 verbose stack     at async CI.exec (/usr/local/lib/node_modules/npm/lib/commands/ci.js:37:5)
37 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
38 verbose cwd /Users/pektezola/Commencis/Code/liveness-detection-framework/source/client
39 verbose Darwin 22.2.0
40 verbose node v18.13.0
41 verbose npm  v8.19.3
42 error code EUSAGE
43 error
43 error The `npm ci` command can only install with an existing package-lock.json or
43 error npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
43 error later to generate a package-lock.json file, then try again.
43 error
43 error Clean install a project
43 error
43 error Usage:
43 error npm ci
43 error
43 error Options:
43 error [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
43 error [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
43 error [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
43 error [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
43 error [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
43 error [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
43 error [-ws|--workspaces] [--include-workspace-root] [--install-links]
43 error
43 error aliases: clean-install, ic, install-clean, isntall-clean
43 error
43 error Run "npm help ci" for more info
44 verbose exit 1
45 timing npm Completed in 84ms
46 verbose code 1
47 error A complete log of this run can be found in:
47 error     /Users/pektezola/.npm/_logs/2023-01-23T13_24_42_753Z-debug-0.lo

**Comment by krokoko** [comment]
Hi @pektezol-commencis, thank you for bringing this to our attention. While we work on a fix, could you please try to replace the [line 77](https://github.com/aws-solutions/liveness-detection-framework/blob/main/deployment/build-s3-dist.sh#L77) in ```build-s3-dist.sh``` from ```npm ci``` to ```npm install --legacy-peer-deps``` and let us know if this works for you ? Thanks

**Comment by ghost** [comment]
Hello @krokoko,

Your suggestion fixed the issue for the script. Then, I uploaded distributable assets to the S3 bucket.
Now, however, it fails when creating the CloudFormation stack:

Embedded stack arn:aws:cloudformation:eu-west-1:-:stack/liveness-BackendStack-1GS9DVXFIQDB/c9856a10-9b56-11ed-9c84-06bbd5c2a299 was not successfully created: The following resource(s) failed to create: [APIHandler]. 

Finally, it rolls back: The following resource(s) failed to create: [BackendStack]. Rollback requested by user.

Any ideas?

**Comment by krokoko** [comment]
Thank you @pektezol-commencis. I am not able to reproduce this specific issue, could you please try to gather more logs ?

**Comment by ghost** [comment]
Hello @krokoko ,

Apparently, the S3 bucket was in a different region than the region of the stack. Opening a new S3 bucket in the same region fixed the issue and I successfully deployed the stack. Thanks for the help.

**Comment by diego12o** [comment]
Hi! I had the same error and the solution was use `npm install` in the client folder before run `build-s3-dist.sh`. I have not tried add this to `build-s3-dist.sh`, but i think it will work. 

The error was because `npm ci` require a `package-lock.json` file (logs show this).

Pd: sorry my english :')
